Implement keypoint matching
mjh-sakh/Project-bI pull request #39
Opened 2020-11-08 17:09 UTC by olegboev

2020-11-09 00:03 UTC, mjh-sakh requested changes
Please delete env_1d from PR. There is a big change to it in the PR 35 submitted earlier and I don't want to spend time resolving conflicts. 
I got point about cv2.

2020-11-09 03:40 UTC, mjh-sakh commented on Stage1/main.py
> +        image_output = draw_pland_and_frames(plan_with_scan, frame_prev, frame_curr, matches)
Where is def for draw_pland_and_frames?

2020-11-09 03:40 UTC, mjh-sakh commented on Stage1/main.py
> +        if k == 27:
Please add comment on what is key 27 is. Space?

2020-11-09 10:25 UTC, mjh-sakh approved these changes

2020-11-09 10:25 UTC, merged

2020-11-10 18:48 UTC, olegboev commented on Stage1/main.py
> +        image_output = draw_pland_and_frames(plan_with_scan, frame_prev, frame_curr, matches)
See [original commit](https://github.com/mjh-sakh/Project-bI/pull/39/commits/c25b7473fff52254b5d2147b5cd31e03f8e7abef#diff-f6a41ba02203b089e0ffe8ccd261599358dd2c692820ebc2ec809f56386cf97e)